package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(
        ["**/*.rs"],
        exclude = ["**/target/**"],
    ) + ["Cargo.toml"],
)

sh_test(
    name = "test",
    srcs = ["//tools:crate.sh"],
    data = ["//:cargo_workspace"],
    args = [
        "frontal-code-webhooks",
        "test",
    ],
    tags = [
        "rust",
        "test",
    ],
)

sh_test(
    name = "fmt",
    size = "small",
    srcs = ["//tools:crate.sh"],
    data = ["//:cargo_workspace"],
    args = [
        "frontal-code-webhooks",
        "fmt-check",
    ],
    tags = [
        "fmt",
        "rust",
    ],
)

sh_test(
    name = "lint",
    srcs = ["//tools:crate.sh"],
    data = ["//:cargo_workspace"],
    args = [
        "frontal-code-webhooks",
        "clippy",
    ],
    tags = [
        "lint",
        "rust",
    ],
)
