package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(
        ["**/*"],
        exclude = [
            "node_modules/**",
            ".git/**",
            "BUILD.bazel",
        ],
    ),
)

sh_test(
    name = "lint",
    size = "small",
    srcs = ["//tools:extension.sh"],
    data = [":srcs", "//:biome.json", "//:ultracite.json", "//:.gitignore", "package.json"],
    args = [
        "extensions/frontal-code-ide",
        "lint",
    ],
    tags = [
        "lint",
        "typescript",
    ],
)

sh_test(
    name = "build",
    srcs = ["//tools:extension.sh"],
    data = [":srcs", "//:biome.json", "//:ultracite.json", "//:.gitignore", "package.json"],
    args = [
        "extensions/frontal-code-ide",
        "build",
    ],
    tags = [
        "build",
        "typescript",
    ],
)
