apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontal-code-server
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - frontal-code.example.com
      secretName: frontal-code-server-tls
  rules:
    - host: frontal-code.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontal-code-server
                port:
                  number: 8788
