//! {{name}} crate — generated by `frontal-code generators crate`.

pub fn hello() -> &'static str {
    "{{name}}"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        assert_eq!(hello(), "{{name}}");
    }
}
